version: "3.9"
services:
  postgres:
    image: postgres:10.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./DDL/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  run:
    environment:
      - postgres_host=postgres
      - postgres_database=postgres
      - postgres_user=postgres
      - postgres_password=postgres
    image: "dbt_postgres"
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    # command: /bin/bash
    # command: dbt --profiles-dir ./.dbt run
